<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\ShopApp.Contract\ShopApp.Contract.csproj" />
		<ProjectReference Include="..\MyComponents\MyComponents.csproj" />
		<ProjectReference Include="..\ShopApp.Domain\ShopApp.Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
		<!-- лицензия будет лежать рядом с exe -->
		<None Include="license.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
